
# 26
headers = [
    "AgentName",
    "WinRate",
    "MarginError",
    "numTurns",
    "victoryPoints",
    "numRoadsBuilt",
    "devCardsBought",
    "usedDevCards",
    "settlementsBuilt",
    "citiesBuilt",
    "devCardVP",
    "largestArmy",
    "longestRoad",
    "resourcesReceived",
    "totalResourcesReceivedPerTurn",
    "totalResourcesDiscarded",
    "totalResourcesStolen",
    "resourcesFromDevCard",
    "totalResourcesFromDevCard",
    "resourcesFromBankTrade",
    "totalResourcesFromBankTrade",
    "finalResourceProduction",
    "finalTradeRates",
    "setupResourceProduction",
    "totalSetupResourceProduction",
    "setupTradeRates",
    "setupResourceDiversity",
    "turnsForFirstSettlement",
    "noSettlementsBuilt",
    "turnsForFirstCity",
    "noCitysBuilt"
]